### ISSUE TITLE
安装后，配置完成后报错。

### ISSUE THREAD

**Issue by nodeloc** [FoskyM/flarum-issue-tracking-youtrack#1]
![image](https://github.com/user-attachments/assets/d085d479-3718-41fd-a73d-de7ffab88d2d)

测试连接没问题，创建的问题也会同步到 youtrack，但是访问就报错

```
Application.tsx:605  TypeError: FoskyM\IssueTrackingYoutrack\PlatformProvider::buildIssue(): Argument FoskyM/flarum-issue-tracking-youtrack#1 ($issue) must be of type array, string given, called in D:\wwwroot\flarum\vendor\foskym\flarum-issue-tracking-youtrack\src\PlatformProvider.php on line 150 and defined in D:\wwwroot\flarum\vendor\foskym\flarum-issue-tracking-youtrack\src\PlatformProvider.php:52
Stack trace:
#0 D:\wwwroot\flarum\vendor\foskym\flarum-issue-tracking-youtrack\src\PlatformProvider.php(150): FoskyM\IssueTrackingYoutrack\PlatformProvider->buildIssue('invalid_query')
FoskyM/flarum-issue-tracking-youtrack#1 [internal function]: FoskyM\IssueTrackingYoutrack\PlatformProvider->FoskyM\IssueTrackingYoutrack\{closure}('invalid_query')
FoskyM/flarum-issue-tracking#1 D:\wwwroot\flarum\vendor\foskym\flarum-issue-tracking-youtrack\src\PlatformProvider.php(149): array_map(Object(Closure), Array)
FoskyM/flarum-issue-tracking-youtrack#3 D:\wwwroot\flarum\vendor\foskym\flarum-issue-tracking\src\Api\Controller\ListIssuesController.php(56): FoskyM\IssueTrackingYoutrack\PlatformProvider->getIssueList('latest', 0, 15)
#4 D:\wwwroot\flarum\vendor\flarum\core\src\Api\Controller\AbstractSerializeController.php(116): FoskyM\IssueTracking\Api\Controller\ListIssuesController->data(Object(Laminas\Diactoros\ServerRequest), Object(Tobscure\JsonApi\Document))
#5 D:\wwwroot\flarum\vendor\flarum\core\src\Http\RouteHandlerFactory.php(41): Flarum\Api\Controller\AbstractSerializeController->handle(Object(Laminas\Diactoros\ServerRequest))
#6 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Laminas\Diactoros\ServerRequest), Array)
#7 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Closure))
#8 D:\wwwroot\flarum\vendor\flarum\core\src\Api\Middleware\ThrottleApi.php(33): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#9 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Api\Middleware\ThrottleApi->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#10 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#11 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\CheckCsrfToken->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#12 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\ResolveRoute.php(69): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#13 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\ResolveRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#14 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\SetLocale.php(51): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#15 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\SetLocale->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#16 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\AuthenticateWithHeader.php(58): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#17 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#18 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#19 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#20 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\RememberFromCookie.php(52): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#21 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\RememberFromCookie->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#22 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\StartSession.php(61): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#23 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\StartSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#24 D:\wwwroot\flarum\vendor\flarum\core\src\Api\Middleware\FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#25 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#26 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\ParseJsonBody.php(28): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#27 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\ParseJsonBody->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#28 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\HandleErrors.php(57): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#29 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\HandleErrors->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#30 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\InjectActorReference.php(25): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#31 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\InjectActorReference->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#32 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#33 D:\wwwroot\flarum\vendor\middlewares\request-handler\src\RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#34 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Middlewares\RequestHandler->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#35 D:\wwwroot\flarum\vendor\middlewares\base-path-router\src\BasePathRouter.php(99): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#36 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Middlewares\BasePathRouter->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#37 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Middleware\OriginalMessages.php(36): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#38 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Laminas\Stratigility\Middleware\OriginalMessages->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#39 D:\wwwroot\flarum\vendor\middlewares\base-path\src\BasePath.php(73): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#40 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Middlewares\BasePath->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#41 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\ProcessIp.php(24): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#42 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\ProcessIp->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#43 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#44 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\EmptyPipelineHandler))
#45 D:\wwwroot\flarum\vendor\laminas\laminas-httphandlerrunner\src\RequestHandlerRunner.php(73): Laminas\Stratigility\MiddlewarePipe->handle(Object(Laminas\Diactoros\ServerRequest))
#46 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#47 D:\wwwroot\flarum\public\index.php(26): Flarum\Http\Server->listen()
#48 {main}
```

**Comment by FoskyM** [comment]
目前在外有事，可能下个月才有空排查问题。

**Comment by nodeloc** [comment]
是我的问题，我项目 ID 填写错了，更正以后就好了，但是更正后有一个问题，就是正常帖子打开后会报错。这些帖子是安装 issue track 之前发布的。
```
GET http://test.nodeloc.com/api/issue-tracking/issue?id=196

Error: Typed property FoskyM\IssueTracking\AbstractIssue::$id must not be accessed before initialization in D:\wwwroot\flarum\vendor\foskym\flarum-issue-tracking\src\Model\Issue.php:21
Stack trace:
#0 D:\wwwroot\flarum\vendor\foskym\flarum-issue-tracking\src\Api\Controller\ShowIssueController.php(65): FoskyM\IssueTracking\Model\Issue->__construct(Object(FoskyM\IssueTracking\AbstractIssue))
FoskyM/flarum-issue-tracking-youtrack#1 D:\wwwroot\flarum\vendor\flarum\core\src\Api\Controller\AbstractSerializeController.php(116): FoskyM\IssueTracking\Api\Controller\ShowIssueController->data(Object(Laminas\Diactoros\ServerRequest), Object(Tobscure\JsonApi\Document))
FoskyM/flarum-issue-tracking#1 D:\wwwroot\flarum\vendor\flarum\core\src\Http\RouteHandlerFactory.php(41): Flarum\Api\Controller\AbstractSerializeController->handle(Object(Laminas\Diactoros\ServerRequest))
FoskyM/flarum-issue-tracking-youtrack#3 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Laminas\Diactoros\ServerRequest), Array)
#4 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Closure))
#5 D:\wwwroot\flarum\vendor\flarum\core\src\Api\Middleware\ThrottleApi.php(33): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#6 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Api\Middleware\ThrottleApi->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#7 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#8 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\CheckCsrfToken->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#9 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\ResolveRoute.php(69): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#10 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\ResolveRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#11 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\SetLocale.php(51): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#12 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\SetLocale->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#13 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\AuthenticateWithHeader.php(58): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#14 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#15 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#16 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#17 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\RememberFromCookie.php(52): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#18 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\RememberFromCookie->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#19 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\StartSession.php(61): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#20 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\StartSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#21 D:\wwwroot\flarum\vendor\flarum\core\src\Api\Middleware\FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#22 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#23 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\ParseJsonBody.php(28): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#24 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\ParseJsonBody->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#25 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\HandleErrors.php(57): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#26 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\HandleErrors->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#27 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\InjectActorReference.php(25): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#28 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\InjectActorReference->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#29 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#30 D:\wwwroot\flarum\vendor\middlewares\request-handler\src\RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#31 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Middlewares\RequestHandler->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#32 D:\wwwroot\flarum\vendor\middlewares\base-path-router\src\BasePathRouter.php(99): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#33 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Middlewares\BasePathRouter->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#34 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Middleware\OriginalMessages.php(36): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#35 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Laminas\Stratigility\Middleware\OriginalMessages->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#36 D:\wwwroot\flarum\vendor\middlewares\base-path\src\BasePath.php(73): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#37 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Middlewares\BasePath->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#38 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Middleware\ProcessIp.php(24): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#39 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\Next.php(49): Flarum\Http\Middleware\ProcessIp->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#40 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#41 D:\wwwroot\flarum\vendor\laminas\laminas-stratigility\src\MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\EmptyPipelineHandler))
#42 D:\wwwroot\flarum\vendor\laminas\laminas-httphandlerrunner\src\RequestHandlerRunner.php(73): Laminas\Stratigility\MiddlewarePipe->handle(Object(Laminas\Diactoros\ServerRequest))
#43 D:\wwwroot\flarum\vendor\flarum\core\src\Http\Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#44 D:\wwwroot\flarum\public\index.php(26): Flarum\Http\Server->listen()
#45 {main}

```

**Comment by FoskyM** [comment]
> 正常帖子打开后会报错。这些帖子是安装 issue track 之前发布的。

这是一个已知 bug，由于近期无空闲时间，故暂未修复。修复预计短则近几天，长则延期至下个月。感谢反馈。

**Comment by FoskyM** [comment]
此问题关闭，转移至 FoskyM/flarum-issue-tracking#1 

Issue closed and will be processed in FoskyM/flarum-issue-tracking#1
